name: squat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.7
  image_picker: ^0.8.4+10
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.4
  geolocator: ^8.2.0
  uuid: ^3.0.6
  animator: ^3.1.0
  firebase_messaging: ^11.2.6
  timeago: ^3.2.2
  cached_network_image: ^3.2.0
  flutter_svg:
  firebase_core: ^1.12.0
  geocoding: 2.0.2
  rive: ^0.8.1
  badges: ^2.0.2
  grouped_list: ^4.2.0
  syncfusion_flutter_charts: ^19.4.54
  collection: ^1.15.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.0.5
  http: ^0.13.4
  flutter_easyloading: ^3.0.3
  webview_flutter: ^3.0.1
  cloud_functions: ^3.2.8
  rflutter_alert: ^2.0.4
  lottie: ^1.2.2
  odometer: ^3.0.0
  giphy_picker: ^2.0.0
  audioplayers: ^0.20.1
  intl: ^0.17.0
  flag: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/soilder.jpg
    - assets/images/nobully.png
    - assets/images/search.png
    - assets/images/notfound.png
    - assets/rives/squat.riv
    - assets/default_payment_profile_google_pay.json
    - assets/donategirl.json
    - assets/dollar.json
    - assets/grunt.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/images/nobully.png
  fill: true